import Head from 'next/head'
import styled from 'styled-components'

import { BsListNested } from 'react-icons/bs'
import { SideBar } from '@/components/Sidebar'
import { SidebarContainer } from '@/containers/base/SidebarContainer'
import { MusicPlayerContainer } from '@/containers/base/MusicPlayerContainer'

interface LayoutMainProps {
  children: React.ReactNode
}

export const LayoutMain: React.FC<LayoutMainProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Foxbel Music</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/img/foxbel-music-icon@3x.png' />
      </Head>
      <SideBar firstIcon={<BsListNested />} secondIcon={<BsListNested />}>
        <SidebarContainer />
      </SideBar>

      <MainLayoutContainer>
        <div className='container'>
          <div className='sidebar-content'>
            <SidebarContainer />
          </div>
          <div className='data'>{children}</div>
          <div className='music-player'>
            <MusicPlayerContainer />
          </div>
        </div>
      </MainLayoutContainer>
    </>
  )
}

const MainLayoutContainer = styled.main`
  width: 100%;
  //max-width: 200rem;
  padding-right: 20px;
  min-width: 250px;
  margin-bottom: 80px;
  .container {
    width: 100%;
    display: flex;
    position: relative;
    .sidebar-content {
      display: none;
      width: fit-content;
      @media (min-width: 1024px) {
        display: block;
      }
    }
    .data {
      width: 100%;
    }
    .music-player {
      bottom: 0;
      width: 100%;
      height: 100px;
      position: fixed;
      box-shadow: 0px -2px 4px rgba(0, 0, 0, 0.25);
      background-color: ${({ theme }) => theme.palette.primary.main};
    }
  }
`
